# fly.toml app configuration file generated for book-management-with-bun on 2023-09-11T17:42:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "book-management-with-bun"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
